name: CI-CD

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:
    
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
    
      - name: Construção da imagem Docker do blue page
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/live-color:${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
      
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: fabricioveronez/live-color:${{ github.run_number }}
          containerAppName: live-aca
          resourceGroup: live-aca


